"""Score round-5 forecasts: baselines, v2.1 (saved rows), round-5 candidates, selection and ablations.

All predictors are scored on the shared held-out rows (participant holdout, round-3 folds).
R2 differences and NLL differences get participant-bootstrap 95% intervals (1000 resamples).
Selection: for each sample and outer fold, the candidate with the best mean inner-validation R2 over
h = 1..6 is chosen without reference to the test fold; "r5_selected" assembles those choices.
NLL: every predictor is scored with its leave-fold-out residual variance (uniform across predictors);
state-space models are also scored with their own predictive variance.
Writes out/score.json, out/score.md, ../../figures/fig_forecast_r5.png.
Run:  python score.py [--abl <base config>]
"""
from __future__ import annotations

import argparse
import json
import pickle
from collections import defaultdict

import numpy as np

from common import (HORIZONS, OUT, ROOT, SAMPLES, boot_mean_diff, boot_r2_diff, common_keys, folds_of, lfo_var,
                    load, load_sample, load_v21_rows, nll_rows, r2_of, records)
from run_r5 import ABLATIONS, CANDIDATES

BASELINES = ("ridge_tt", "pmean_all", "pmean_seg", "ridge_pm_all", "ridge_pm_seg", "ebar1",
             "kf_all_h1", "kf_all_h6", "kf_seg_h1", "kf_seg_h6", "kfvol_all_h1", "kfvol_all_h6")
V21_VARIANTS = ("gated", "inert", "no_channels", "no_level2", "clampPRESENT", "no_baseline")


def load_r5(sample, cfg, stage):
    pred, var = {h: {} for h in HORIZONS}, {h: {} for h in HORIZONS}
    state, per_fold = {}, {}
    for k in range(5):
        f = OUT / f"r5_{sample}_{cfg}_{stage}_k{k}.pkl"
        if not f.exists():
            return None
        with open(f, "rb") as fh:
            z = pickle.load(fh)
        per_fold[k] = z
        for h in HORIZONS:
            pred[h].update(z["pred"][h])
            var[h].update(z["var"][h])
        state.update(z["state"])
    return dict(pred=pred, var=var, state=state, folds=per_fold)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--abl", default=None, help="base config whose ablations to score")
    args = ap.parse_args()
    report = {}
    md = ["# Round-5 forecasting scores (generated by score.py)", ""]
    for sample in SAMPLES:
        parts, has_event = load_sample(sample)
        pids = sorted(parts)
        fold = folds_of(pids)
        recs = records(parts, has_event)
        base = load(f"baselines_{sample}.pkl")
        oof, own = {}, {}
        for b in BASELINES:
            if b in base["oof"]:
                oof[b] = base["oof"][b]
                if b in base["S"]:
                    own[b] = base["S"][b]
        for n in ("kfx_all_h1", "kfx_all_h6", "kfx0_all_h1"):
            if n in base["oof"]:
                oof[n] = base["oof"][n]
                own[n] = base["S"][n]
        for v in V21_VARIANTS:
            rows = load_v21_rows(sample, v, pids)
            if rows is None:
                continue
            oof[f"v21_{v}"] = {h: {key: float(val[0][h - 1]) for key, val in rows.items()} for h in HORIZONS}
            own[f"v21_{v}"] = {h: {key: float(val[1][h - 1]) for key, val in rows.items()} for h in HORIZONS}
        # round-5 candidates (outer) and selection from inner validation
        sel_log = {}
        cand_outer = {}
        for cfg in CANDIDATES:
            o = load_r5(sample, cfg, "outer")
            if o is not None:
                cand_outer[cfg] = o
                oof[f"r5_{cfg}"] = o["pred"]
                own[f"r5_{cfg}"] = o["var"]
        inner_scores = defaultdict(dict)
        for cfg in CANDIDATES:
            inn = load_r5(sample, cfg, "inner")
            if inn is None:
                continue
            for k, z in inn["folds"].items():
                vp = {key[0] for key in z["pred"][1]}
                rs = [r for r in recs if r["pid"] in vp]
                inner_scores[k][cfg] = float(np.mean([r2_of(rs, z["pred"], h)[0] for h in HORIZONS]))
        if inner_scores and all(len(inner_scores[k]) == len(cand_outer) == len(CANDIDATES) for k in range(5)):
            sel = {k: max(inner_scores[k], key=inner_scores[k].get) for k in range(5)}
            sel_log = dict(selected=sel, inner=inner_scores)
            oof["r5_selected"] = {h: {} for h in HORIZONS}
            own["r5_selected"] = {h: {} for h in HORIZONS}
            for h in HORIZONS:
                for key, pv in next(iter(cand_outer.values()))["pred"][h].items():
                    cfg = sel[fold[key[0]]]
                    oof["r5_selected"][h][key] = cand_outer[cfg]["pred"][h][key]
                    own["r5_selected"][h][key] = cand_outer[cfg]["var"][h][key]
        if args.abl:
            for ab in ABLATIONS:
                o = load_r5(sample, f"{args.abl}+{ab}", "outer")
                if o is not None:
                    oof[f"abl_{ab}"] = o["pred"]
                    own[f"abl_{ab}"] = o["var"]
        names = list(oof)
        # shared rows
        keys = {h: common_keys(recs, [oof[n] for n in names], h) for h in HORIZONS}
        tab = {n: {h: r2_of(recs, oof[n], h, keys[h])[0] for h in HORIZONS} for n in names}
        nrows = {h: len(keys[h]) for h in HORIZONS}
        bl = [b for b in BASELINES if b in oof]
        best_bl = {h: max(bl, key=lambda b: tab[b][h]) for h in HORIZONS}
        models = [n for n in names if n.startswith(("v21_gated", "v21_inert", "v21_no_channels", "r5_", "abl_", "kfx"))]
        cis = []
        for n in models:
            for h in HORIZONS:
                for b in sorted({best_bl[h], "ridge_tt", "ridge_pm_all", "kf_all_h1"} & set(bl)):
                    pt, lo, hi = boot_r2_diff(recs, oof[n], oof[b], h, keys[h])
                    cis.append(dict(a=n, b=b, h=h, point=pt, lo=lo, hi=hi))
        # model vs model comparisons
        pairs = [(a, b) for a, b in (("kfx_all_h1", "kfx0_all_h1"), ("kfx_all_h6", "kfx0_all_h1"), ("kfx_all_h1", "kfvol_all_h1"),
                                     ("kfvol_all_h1", "kf_all_h1"), ("kfx_all_h1", "r5_sp_h6_vol")) if a in oof and b in oof]
        if "r5_selected" in oof:
            pairs += [("r5_selected", "v21_gated")] + [(f"r5_{c}", "v21_gated") for c in CANDIDATES if f"r5_{c}" in oof]
        if args.abl:
            sel_name = f"r5_{args.abl}"
            pairs += [(f"abl_{ab}", sel_name) for ab in ABLATIONS if f"abl_{ab}" in oof]
        for a, b in pairs:
            for h in HORIZONS:
                pt, lo, hi = boot_r2_diff(recs, oof[a], oof[b], h, keys[h])
                cis.append(dict(a=a, b=b, h=h, point=pt, lo=lo, hi=hi))
        # NLL: leave-fold-out residual variance for all, own predictive variance for state-space models
        nll = {}
        nll_rows_cache = {}
        for n in names:
            for kind, var in (("lfo", {h: lfo_var(recs, oof[n], h, fold) for h in HORIZONS}), ("own", own.get(n))):
                if var is None:
                    continue
                for h in HORIZONS:
                    rw = nll_rows(recs, oof[n], var, h, keys[h])
                    nll_rows_cache[(n, kind, h)] = rw
                    nll.setdefault(n, {}).setdefault(kind, {})[h] = float(np.concatenate(list(rw.values())).mean())
        nll_cis = []
        for n in [m for m in models if m in own]:
            for h in HORIZONS:
                cands = [(b, kind) for b in bl for kind in ("lfo", "own") if (b, kind, h) in nll_rows_cache]
                bb, bk = min(cands, key=lambda c: nll[c[0]][c[1]][h])
                pt, lo, hi = boot_mean_diff(nll_rows_cache[(n, "own", h)], nll_rows_cache[(bb, bk, h)])
                nll_cis.append(dict(a=n, b=f"{bb}/{bk}", h=h, point=pt, lo=lo, hi=hi))
        # channels: change after events (Geschwind), selected model vs its no-channel ablation
        events = {}
        if has_event:
            ev = lambda r: r["e"] != 0.0
            q75 = float(np.percentile([abs(r["e"]) for r in recs if r["e"] != 0.0], 75))
            big = lambda r: abs(r["e"]) >= q75
            for sname, sub in (("after_event", ev), ("after_big_event", big)):
                for h in (1, 2, 3, 6):
                    rows = [r for r in recs if (r["pid"], r["i"]) in keys[h] and sub(r)]
                    ksub = {(r["pid"], r["i"]) for r in rows}

                    def chg(n):
                        ys = np.array([r[f"y{h}"] - r["v"] for r in rows])
                        ps = np.array([oof[n][h][(r["pid"], r["i"])] - r["v"] for r in rows])
                        return float(1 - np.sum((ys - ps) ** 2) / np.sum((ys - ys.mean()) ** 2))
                    entry = {n: chg(n) for n in names if n.startswith(("r5_", "abl_", "v21_gated", "v21_no_channels", "ridge_pm", "ridge_tt", "kf"))}
                    # bootstrap on change R2 for selected or base minus its no-channel ablation
                    chg_oof = lambda n: {h: {key: oof[n][h][key] - rec_v[key] for key in ksub}}
                    rec_v = {(r["pid"], r["i"]): r["v"] for r in rows}
                    rec_c = {}
                    for r in rows:
                        rec_c[(r["pid"], r["i"])] = dict(r)
                        rec_c[(r["pid"], r["i"])][f"y{h}"] = r[f"y{h}"] - r["v"]
                    crecs = list(rec_c.values())
                    comps = {}
                    for a, b in (("abl_no_channels", f"r5_{args.abl}" if args.abl else None),
                                 ("v21_no_channels", "v21_gated"), ("r5_selected", "ridge_pm_all"), ("r5_selected", "ridge_tt"),
                                 ("kfx_all_h1", "kfx0_all_h1"), ("kfx_all_h6", "kfx0_all_h1"), ("kfx_all_h1", "ridge_pm_seg")):
                        if a in oof and b in oof:
                            comps[f"{a}-{b}"] = boot_r2_diff(crecs, chg_oof(a), chg_oof(b), h, ksub)
                    nll_comp = {}
                    for a, b in (("abl_no_channels", f"r5_{args.abl}" if args.abl else None), ("v21_no_channels", "v21_gated"),
                                 ("kfx_all_h1", "kfx0_all_h1"), ("kfx_all_h6", "kfx0_all_h1")):
                        if a in own and b in own:
                            ra = nll_rows(recs, oof[a], own[a], h, ksub)
                            rb = nll_rows(recs, oof[b], own[b], h, ksub)
                            nll_comp[f"{a}-{b}"] = boot_mean_diff(ra, rb)
                    events[f"{sname}_h{h}"] = dict(n=len(rows), r2_change=entry, boot=comps, nll=nll_comp)
        report[sample] = dict(r2=tab, nrows=nrows, best_baseline=best_bl, cis=cis, nll=nll, nll_cis=nll_cis,
                              selection=sel_log, events=events,
                              kf_params=base["info"].get("kf"), ridge_info=base["info"].get("ridge"),
                              ebar1_info=base["info"].get("ebar1"))
        md.append(f"## {sample}")
        md.append("")
        md.append("| predictor | " + " | ".join(f"h={h}" for h in HORIZONS) + " |")
        md.append("|---|" + "---:|" * len(HORIZONS))
        for n in names:
            md.append(f"| {n} | " + " | ".join(f"{tab[n][h]:.3f}" for h in HORIZONS) + " |")
        md.append("")
        md.append("rows: " + ", ".join(f"h{h} {nrows[h]}" for h in HORIZONS))
        md.append("best baseline: " + ", ".join(f"h{h} {best_bl[h]}" for h in HORIZONS))
        if sel_log:
            md.append("selection per fold: " + json.dumps(sel_log["selected"]))
        md.append("")
        for c in cis:
            md.append(f"- h={c['h']} {c['a']} - {c['b']}: {c['point']:+.4f} [{c['lo']:+.4f}, {c['hi']:+.4f}]")
        md.append("")
        md.append("NLL (lfo = leave-fold-out residual variance; own = model's predictive variance)")
        for n in names:
            for kind in nll.get(n, {}):
                md.append(f"- {n} {kind}: " + ", ".join(f"h{h} {nll[n][kind][h]:.4f}" for h in HORIZONS))
        for c in nll_cis:
            md.append(f"- NLL h={c['h']} {c['a']}(own) - {c['b']}: {c['point']:+.4f} [{c['lo']:+.4f}, {c['hi']:+.4f}]")
        if events:
            md.append("")
            md.append("Change after events")
            for k_, v_ in events.items():
                md.append(f"- {k_} n={v_['n']}: " + json.dumps({a: round(b, 4) for a, b in v_["r2_change"].items()}))
                for a, b in v_["boot"].items():
                    md.append(f"  - R2 change {a}: {b[0]:+.4f} [{b[1]:+.4f}, {b[2]:+.4f}]")
                for a, b in v_["nll"].items():
                    md.append(f"  - NLL {a}: {b[0]:+.4f} [{b[1]:+.4f}, {b[2]:+.4f}]")
        md.append("")
        print(f"[{sample}] scored", flush=True)
    (OUT / "score.json").write_text(json.dumps(report, indent=1, default=float), encoding="utf-8")
    (OUT / "score.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    print("written out/score.json, out/score.md", flush=True)


if __name__ == "__main__":
    main()
